# logging.level.com.microsoft=debug
# logging.level.com.azure=debug
# logging.level.io.netty=debug
# logging.level.reactor.netty=debug

spring.mvc.async.request-timeout=300000

# client-openai-key: set via env variable
client-openai-endpoint=https://ai-proxy.lab.epam.com
client-openai-endpoint-model-list=${client-openai-endpoint}/openai/deployments

weather_api_url=https://api.weatherapi.com/v1/
# weather_api_key=get key from www.weatherapi.com

app.embedding.datasource.jdbcUrl=jdbc:postgresql://postgres:5432/postgres
app.embedding.datasource.username=postgres
app.embedding.datasource.password=semantic-kernel
app.embedding.datasource.driverClassName=org.postgresql.Driver
