# logging.level.com.microsoft=debug
# logging.level.com.azure=debug
# logging.level.io.netty=debug
# logging.level.reactor.netty=debug

# client-openai-key: set via env variable
client-openai-endpoint=https://ai-proxy.lab.epam.com
client-openai-endpoint-model-list=${client-openai-endpoint}/openai/deployments

weather_api_url=https://api.weatherapi.com/v1/
# weather_api_key: get key from www.weatherapi.com
